# Generated by Django 3.2.13 on 2022-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzed_Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetId', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=300)),
                ('hateValue', models.FloatField()),
                ('loc_lat', models.FloatField()),
                ('loc_lng', models.FloatField()),
                ('dateOfTweet', models.CharField(max_length=200)),
                ('dateOfPrediction', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
